include ':TMessagesProj'
include ':TMessagesProj_App'
include ':TMessagesProj_AppHuawei'
include ':TMessagesProj_AppHockeyApp'
include ':TMessagesProj_AppStandalone'
include ':TMessagesProj_AppTests'
include ':jlatexmath'
project(':jlatexmath').projectDir = file('TMessagesProj/lib/jlatexmath/jlatexmath')
