package org.telegram.tasks.localization

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.nio.charset.StandardCharsets
import kotlin.text.iterator

@CacheableTask
abstract class GenerateLocalizationUtilsJavaTask : DefaultTask() {

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val localizationFiles: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val javaOutputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val localizations = sortedSetOf<String>()

        // Default localization always exists.
        localizations.add("en")

        for (file in localizationFiles.files) {
            localizations.add(getLanguageTag(file))
        }

        generateJava(
            javaDir = javaOutputDir.get().asFile,
            languageTags = localizations
        )
    }

    private fun generateJava(
        javaDir: File,
        languageTags: Set<String>
    ) {
        val packageName = "org.telegram.localization"
        val packageDir = javaDir.resolve(packageName.replace('.', '/'))

        packageDir.mkdirs()

        packageDir.resolve("LocalizationUtils.java")
            .bufferedWriter(StandardCharsets.UTF_8)
            .use { java ->
                java.appendLine("package $packageName;")
                java.appendLine()
                java.appendLine("import java.util.Locale;")
                java.appendLine()
                java.appendLine("/** Generated by TelegramLocalizationJavaTask. Do not edit. */")
                java.appendLine("public final class LocalizationUtils {")
                java.appendLine()
                java.appendLine("    public static final String DEFAULT_LOCALIZATION = \"localization_en.bin\";")
                java.appendLine()
                java.appendLine("    private LocalizationUtils() {")
                java.appendLine("    }")
                java.appendLine()
                java.appendLine("    public static String getLocalizationAsset(Locale locale) {")
                java.appendLine("        if (locale == null) {")
                java.appendLine("            return null;")
                java.appendLine("        }")
                java.appendLine()
                java.appendLine("        final String tag = locale.toLanguageTag();")
                java.appendLine()
                java.appendLine("        switch (tag) {")

                for (tag in languageTags) {
                    java.append("            case \"")
                    java.append(escapeJavaString(tag))
                    java.append("\": return \"")
                    java.append(getLocalizationAssetName(tag))
                    java.appendLine("\";")
                }

                java.appendLine("        }")
                java.appendLine()
                java.appendLine("        final String language = locale.getLanguage();")
                java.appendLine()
                java.appendLine("        switch (language) {")

                for (tag in languageTags) {
                    if (!tag.contains('-')) {
                        java.append("            case \"")
                        java.append(escapeJavaString(tag))
                        java.append("\": return \"")
                        java.append(getLocalizationAssetName(tag))
                        java.appendLine("\";")
                    }
                }

                java.appendLine("            default: return null;")
                java.appendLine("        }")
                java.appendLine("    }")
                java.appendLine("}")
            }
    }

    private fun getLocalizationAssetName(
        languageTag: String
    ): String {
        val normalized = buildString(languageTag.length) {
            for (char in languageTag) {
                when {
                    char in 'A'..'Z' -> append(char.lowercaseChar())
                    char in 'a'..'z' ||
                            char in '0'..'9' ||
                            char == '_' -> append(char)

                    else -> append('_')
                }
            }
        }

        return "localization_$normalized.bin"
    }

    private fun getLanguageTag(
        file: File
    ): String {
        val directoryName = file.parentFile.name

        if (!directoryName.startsWith("values-")) {
            error("Invalid localization directory: ${file.absolutePath}")
        }

        val qualifier = directoryName.substring("values-".length)

        if (qualifier.isEmpty()) {
            error("Unable to determine language code: ${file.absolutePath}")
        }

        if (qualifier.startsWith("b+")) {
            return qualifier.substring(2).replace('+', '-')
        }

        val regionIndex = qualifier.indexOf("-r")

        if (regionIndex != -1) {
            val language = qualifier.substring(0, regionIndex)
            val region = qualifier.substring(regionIndex + 2)

            return "$language-$region"
        }

        return qualifier
    }

    private fun escapeJavaString(
        value: String
    ): String {
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
    }
}