name: Build Devgram APK - Remastered by Dev

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          sdkmanager --install "ndk;25.1.8937393"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.1.8937393" >> $GITHUB_ENV

      - run: chmod +x gradlew

      - name: Set API ID and Hash from GitHub Secrets
        run: |
          sed -i "s/APP_ID = .*/APP_ID = ${{ secrets.API_ID }};/" TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java
          sed -i 's/APP_HASH = ".*"/APP_HASH = "${{ secrets.API_HASH }}";/' TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java

      - name: Build Devgram Release APK
        run: ./gradlew assembleAfatRelease --no-daemon -Dorg.gradle.jvmargs="-Xmx4g"

      - uses: actions/upload-artifact@v4
        with:
          name: Devgram-APK-Remastered-by-Dev
          path: |
            TMessagesProj/build/outputs/apk/afat/release/*.apk

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0-${{ github.run_number }}
          name: Devgram - Remastered by Dev
          files: TMessagesProj/build/outputs/apk/afat/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
